name: Build and Package MissionController

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  VERSION: "1.3"

jobs:
  package-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pywinpty
          pip install -r requirements.txt

      - name: Build Java Project
        run: mvn clean package
        working-directory: MissionControllerUI

      - name: Package Java App
        run: |
          jpackage --name MissionController `
                   --input MissionControllerUI/target `
                   --main-jar star-1.0-SNAPSHOT-jar-with-dependencies.jar `
                   --main-class org.ariss.star.Main `
                   --type app-image `
                   --dest dist `
                   --app-version $env:VERSION

      - name: Package Python App
        run: pyinstaller --distpath dist --workpath build --hidden-import winpty --hidden-import pywinpty backend.py

      - name: Download Binaries from Release
        run: |
          $outDir = "MissionController-windows-v${env:VERSION}"
          mkdir $outDir

          Invoke-WebRequest -Uri "https://github.com/unshrawal/star-binaries/releases/download/1.0/direwolf.exe" -OutFile "$outDir/direwolf.exe"
          Invoke-WebRequest -Uri "https://github.com/unshrawal/star-binaries/releases/download/1.0/gen_packets.exe" -OutFile "$outDir/gen_packets.exe"
          Invoke-WebRequest -Uri "https://github.com/unshrawal/star-binaries/releases/download/1.0/gpredict-win32-2.2.1.zip" -OutFile "gpredict-win32-2.2.1.zip"
          Expand-Archive -Path "gpredict-win32-2.2.1.zip" -DestinationPath "$outDir"

          Invoke-WebRequest -Uri "https://github.com/unshrawal/star-binaries/releases/download/1.0/MARS-SIM.zip" -OutFile "MARS-SIM.zip"
          Expand-Archive -Path "MARS-SIM.zip" -DestinationPath "$outDir"
        
      - name: Rename and Organize Output
        run: |
          $outDir = "MissionController-windows-v${env:VERSION}"
          Move-Item dist $outDir\dist
          Copy-Item direwolf-win.conf -Destination $outDir
          Copy-Item launcher.bat -Destination $outDir
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: missioncontroller-windows
          path: MissionController-windows-v${{ env.VERSION }}

  package-linux:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Install Liberica JDK 21 Full (with JavaFX)
        run: |
          sudo mkdir -m 0755 -p /etc/apt/keyrings/
          wget -q -O - https://download.bell-sw.com/pki/GPG-KEY-bellsoft | gpg --dearmor | sudo tee /etc/apt/keyrings/GPG-KEY-bellsoft.gpg > /dev/null
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/GPG-KEY-bellsoft.gpg] https://apt.bell-sw.com/ stable main" | sudo tee /etc/apt/sources.list.d/bellsoft.list
          sudo apt-get update
          sudo apt-get install -y bellsoft-java21-full

      - name: Set JAVA_HOME
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/bellsoft-java21-full" >> $GITHUB_ENV
          echo "/usr/lib/jvm/bellsoft-java21-full/bin" >> $GITHUB_PATH

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          sudo apt install -y librtlsdr-dev libusb-1.0-0-dev build-essential cmake pkg-config
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build Java Project
        run: mvn clean package
        working-directory: MissionControllerUI

      - name: Package Java App
        run: |
          jpackage --name MissionController \
                   --input MissionControllerUI/target \
                   --main-jar star-1.0-SNAPSHOT-jar-with-dependencies.jar \
                   --main-class org.ariss.star.Main \
                   --type app-image \
                   --dest dist \
                   --app-version $VERSION

      - name: Package Python App
        run: pyinstaller --distpath dist --workpath build backend.py

      - name: Download WebGL Mars Sim from Release
        run: |
          outDir="MissionController-linux-v$VERSION"
          mkdir "$outDir"
          curl -L -o "webGL_Mars_Sim.zip" https://github.com/unshrawal/star-binaries/releases/download/1.0/webGL_Mars_Sim.zip
          unzip webGL_Mars_Sim.zip -d "$outDir"

      - name: Download QSSTV Binary
        run: |
          outDir="MissionController-linux-v$VERSION"
          curl -L -o "$outDir/qsstv" https://github.com/unshrawal/star-binaries/releases/download/1.0/qsstv
          
      - name: Rename and Organize Output
        run: |
          outDir="MissionController-linux-v$VERSION"
          mv dist "$outDir/dist"
          cp cleanup.sh direwolf.conf script.sh start.sh "$outDir/"
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: missioncontroller-linux
          path: MissionController-linux-v${{ env.VERSION }}
